spring.application.name=salon-gestion-api

# ==============================================================
# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL)
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/salon_gestion_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==============================================================
# "update" creará/actualizará las tablas automáticamente según tus Entities
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en consola
spring.jpa.show-sql=true
# Formatea el SQL para que sea más legible en consola
spring.jpa.properties.hibernate.format_sql=true
# Dialecto específico para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================================================
# CONFIGURACIÓN DEL SERVIDOR
# ==============================================================
server.port=8080

# ==============================================================
# CONFIGURACIÓN JWT (RSA Keys)
# ==============================================================
jwt.private-key-path=classpath:private_key.pem
jwt.public-key-path=classpath:public_key.pem
# Expiración en milisegundos: 3600000 = 1 hora
jwt.expiration=3600000
